import { dehydrate, DehydratedState, QueryClient } from "@tanstack/react-query";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import PostCreate from "../components/post-create";

import PostList from "../components/post-list";

import { DEFAULT_PAGINATE, fetchPosts } from "../services/post.service";

type HomePageProps = {
    dehydratedState: DehydratedState;
};

const Home: NextPage<HomePageProps> = () => {
    return (
        <div className="max-w-4xl mx-auto py-10">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex justify-between space-x-20">
                <div className="flex-1">
                    <PostCreate />
                </div>
                <div className="flex-1">
                    <PostList />
                </div>
            </div>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async () => {
    const queryClient = new QueryClient();
    await queryClient.prefetchQuery(["posts", "list"], () =>
        fetchPosts({
            ...DEFAULT_PAGINATE,
        })
    );
    return {
        props: {
            dehydratedState: dehydrate(queryClient),
        },
    };
};

export default Home;
